### ISSUE TITLE
Web status check is hardcoded for port 8080

### ISSUE THREAD

**Issue by vsilverman** [rpetrenko/hypercenter#3]
Currently **installer** checks status of the Web app, which running only on http://localhost:8080.

Does it make sense to make the port number for this check configurable via **.env file**?

**Comment by rpetrenko** [comment]
yes, thanks

**Comment by rpetrenko** [comment]
actually, no. django runs on port 8080 (hardcoded) in container, but to avoid port clash the external port of the host can be set in .env, and that's what installer is using.
